# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return ;;
esac

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# Make any command 200% more kawaii
_kawaiify() {
  local cmd args i
  cmd=$1
  shift
  let i=0
  while (($# > 0))
  do
    arg=$1
    case "$arg"
    in
      --kawaii|--kawaii=*)
        arg="--pretty${arg#--kawaii}"
        ;;
    esac
    args[$i]=$arg
    let i++
    shift
  done
  "$cmd" "${args[@]}"
}
# alias git="_kawaiify git"

alias vi="vim"

export EDITOR="vim"
export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
export PATH="$PATH:$HOME/.local/bin"

# Borg
export BORG_REPO="/run/media/$USER/StoreJetBackups/borg"

# Rust
export PATH="$PATH:$HOME/.cargo/bin"

# Go
export GOPATH="$HOME/src/go"

# kubectl
if test "$(which kubectl 2>/dev/null)"
then
    source <(kubectl completion bash)
    alias k=kubectl
    complete -F __start_kubectl k
fi

# krew
export PATH="$PATH:$HOME/.krew/bin"

# minikube
if test "$(which minikube 2>/dev/null)"
then
    source <(minikube completion bash)
fi

# CRC
export PATH="$PATH:$HOME/.crc/bin"

# Google Cloud SDK
if test -d ~/.google-cloud-sdk
then
    . ~/.google-cloud-sdk/path.bash.inc
    . ~/.google-cloud-sdk/completion.bash.inc
fi

# KubeVirt
export KUBEVIRT_PROVIDER=k8s-1.18

# . /usr/share/git-core/contrib/completion/git-prompt.sh
# export GIT_PS1_SHOWDIRTYSTATE=1
# export PS1='[\u@\h$(__git_ps1 " (%s)") \W]\$ '

# powerline-daemon -q
# . /usr/share/powerline/bash/powerline.sh

. ~/.promptline.sh

set -o vi
