#!/bin/sh

set -e

if test "$RCRC" && test -e "$RCRC"; then
    . "$RCRC"
elif test -e ~/.rcrc; then
    . ~/.rcrc
fi

TOPDIR="$(dirname "$0")/../.."
SECRETDIR="$TOPDIR/_secret"

if ! test -d "$SECRETDIR"; then
   exit 0
fi

tmpfile=$(mktemp)
cleanup() {
    rm -f "$tmpfile"
}
trap cleanup EXIT

for secretfile in $(find "$SECRETDIR" -name "*.asc" -printf "%P\n"); do
    secretpath=$(dirname "$secretfile")
    secretname=$(basename "$secretfile" .asc)

    echo "secret: decrypting $secretpath/$secretname"
    gpg -q --decrypt "$SECRETDIR/$secretfile" >"$tmpfile"

    mkdir -p "$TOPDIR/$secretpath"
    cp "$tmpfile" "$TOPDIR/$secretpath/$secretname"
done
