#!/bin/sh

set -e

process() {
    secretfile="$1"

    secretpath=$(dirname "$secretfile")
    secretname=$(basename "$secretfile" .asc)

    echo "secret: decrypting $secretpath/$secretname"
    gpg -q --decrypt "$SECRETDIR/$secretfile" >"$TMPFILE"

    mkdir -p "$TOPDIR/$secretpath"
    cp "$TMPFILE" "$TOPDIR/$secretpath/$secretname"
}

cleanup() {
    rm -f "$TMPFILE"
}

if test "$RCRC" && test -e "$RCRC"; then
    . "$RCRC"
elif test -e ~/.rcrc; then
    . ~/.rcrc
fi

TOPDIR="$(dirname "$0")/../.."
SECRETDIR="$TOPDIR/_secret"

if ! test -d "$SECRETDIR"; then
   exit 0
fi

TMPFILE=$(mktemp)
trap cleanup EXIT

for secretfile in $(find "$SECRETDIR" -name "*.asc" -printf "%P\n"); do
    process "$secretfile"
done
