set nocompatible

" Keep $HOME tidy
set viminfo+=n~/.vim/viminfo
set viminfofile=~/.vim/viminfo

" Install vim-plug if not already present
if empty(glob('~/.vim/autoload/plug.vim'))
    !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-plug'

Plug 'morhetz/gruvbox'

Plug 'vim-airline/vim-airline'

Plug 'romainl/vim-cool'

Plug 'ervandew/supertab'

Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete-omni.vim'

Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

Plug 'fatih/vim-go'

call plug#end()

" Use gruvbox theme
set background=dark
colorscheme gruvbox

" Show line numbers
set number

" Mark the 80 column limit
set colorcolumn=80

" Make command mode completion more usable
set wildmenu
set wildmode=longest:full

" Always show the status line
set laststatus=2

" Use powerline fonts for the status line
let g:airline_powerline_fonts = 1

" Perform case-insensitive search unless the pattern contains
" uppercase letters
set ignorecase
set smartcase

" Search incrementally and highlight matches
set incsearch
set hlsearch

" Make insert mode completion more usable
set completeopt=longest,menuone,popup

" Configure supertab
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"
let g:SuperTabLongestHighlight = 1
let g:SuperTabCrMapping = 1
let g:SuperTabCompleteCase = "ignore"
let g:SuperTabClosePreviewOnPopupClose = 1
