set nocompatible

" Keep $HOME tidy
set viminfo+=n~/.vim/viminfo
set viminfofile=~/.vim/viminfo

" Install vim-plug if not already present
if empty(glob('~/.vim/autoload/plug.vim'))
    !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-plug'

Plug 'morhetz/gruvbox'

Plug 'vim-airline/vim-airline'

Plug 'romainl/vim-cool'

Plug 'ervandew/supertab'

Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete-omni.vim'

Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

Plug 'fatih/vim-go'

Plug 'rust-lang/rust.vim'

Plug 'tpope/vim-fugitive'

call plug#end()

" Use UTF-8
set encoding=utf-8

" Use gruvbox theme
set background=dark
colorscheme gruvbox

" Show line numbers
set number

" Mark the 80 column limit
set colorcolumn=80

" Make command mode completion more usable
set wildmenu
set wildmode=longest:full

" Always show the status line
set laststatus=2

" Customize the status line
let g:airline_powerline_fonts = 1
let g:airline#extensions#scrollbar#enabled = 0
if !exists("g:airline_symbols")
    let g:airline_symbols = {}
endif
let g:airline_symbols.linenr = " "
let g:airline_symbols.maxlinenr = ""
let g:airline_symbols.colnr = ":"

" Perform case-insensitive search unless the pattern contains
" uppercase letters
set ignorecase
set smartcase

" Search incrementally and highlight matches
set incsearch
set hlsearch

" Make insert mode completion more usable
set completeopt=longest,menuone,popup

" Configure supertab
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"
let g:SuperTabLongestHighlight = 1
let g:SuperTabCrMapping = 1
let g:SuperTabCompleteCase = "ignore"
let g:SuperTabClosePreviewOnPopupClose = 1

" Wrap text to 70 columns
set textwidth=69

" Indent automatically
set autoindent
set smartindent

" Use spaces instead of tabs, except when editing make rules
set expandtab
autocmd FileType make,automake setlocal noexpandtab

" Indentation is usually 4 spaces, but only 2 spaces are used
" for XML files
set tabstop=4
set shiftwidth=4
autocmd FileType xml setlocal tabstop=2
autocmd FileType xml setlocal shiftwidth=2

" Abbreviations for git
let s:gitname = systemlist("git config user.name")[0]
let s:gitemail = systemlist("git config user.email")[0]
execute "iabbrev gsob Signed-off-by: " . s:gitname . " <" . s:gitemail . ">"
execute "iabbrev gack Reviewed-by: " . s:gitname . " <" . s:gitemail . ">"
unlet s:gitname
unlet s:gitemail

" Other abbreviations
iabbrev shruggy ¯\_(ツ)_/¯
