set nocompatible

" Keep $HOME tidy
set viminfo+=n~/.vim/viminfo
set viminfofile=~/.vim/viminfo

" Install vim-plug if not already present
if empty(glob('~/.vim/autoload/plug.vim'))
    !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-plug'

Plug 'morhetz/gruvbox'

Plug 'vim-airline/vim-airline'

Plug 'romainl/vim-cool'

call plug#end()

" Use gruvbox theme
set background=dark
colorscheme gruvbox

" Show line numbers
set number

" Mark the 80 column limit
set colorcolumn=80

" Make command mode completion more usable
set wildmenu
set wildmode=longest:full

" Always show the status line
set laststatus=2

" Use powerline fonts for the status line
let g:airline_powerline_fonts = 1

" Perform case-insensitive search unless the pattern contains
" uppercase letters
set ignorecase
set smartcase

" Search incrementally and highlight matches
set incsearch
set hlsearch
