set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'

"Plugin 'jeaye/color_coded'
"Plugin 'Valloric/YouCompleteMe'

Plugin 'morhetz/gruvbox'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set background=dark
colorscheme gruvbox

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

set number
set colorcolumn=80
