#!/bin/sh

set -e

process() {
    dconffile="$1"

    dconfpath=$(dirname "$dconffile")
    dconfname=$(basename "$dconffile")
    dconfkey="/$(echo "$dconfname" | tr . /)/"

    # Some applications, for example Tilix, don't react immediately to
    # configuration changes and stay in the "settings reset" state until
    # they are restarted, which can be annoying. If the current settings
    # already match those we would apply, just don't do anything
    dconf dump "$dconfkey" >"$TMPFILE"
    if diff "$DCONFDIR/$dconfpath/$dconfname" "$TMPFILE" >/dev/null 2>&1; then
        return
    fi

    echo "dconf: loading settings for $dconfkey"
    dconf reset -f "$dconfkey"
    dconf load "$dconfkey" <"$DCONFDIR/$dconfpath/$dconfname"
}

cleanup() {
    rm -f "$TMPFILE"
}

if test "$RCRC" && test -e "$RCRC"; then
    . "$RCRC"
elif test -e ~/.rcrc; then
    . ~/.rcrc
fi

TOPDIR="$(dirname "$0")/../.."
DCONFDIR="$TOPDIR/_dconf"

if ! test -d "$DCONFDIR"; then
    exit 0
fi

TMPFILE=$(mktemp)
trap cleanup EXIT

for dconffile in $(find "$DCONFDIR" -maxdepth 1 -type f -printf "%P\n"); do
    process "$dconffile"
done
for tag in $TAGS; do
    if ! test -d "$DCONFDIR/tag-$tag"; then
        continue
    fi
    for dconffile in $(find "$DCONFDIR/tag-$tag" -maxdepth 1 -type f -printf "%P\n"); do
        process "tag-$tag/$dconffile"
    done
done
for host in $HOSTNAME; do
    if ! test -d "$DCONFDIR/host-$host"; then
        continue
    fi
    for dconffile in $(find "$DCONFDIR/host-$host" -maxdepth 1 -type f -printf "%P\n"); do
        process "host-$host/$dconffile"
    done
done
